

pipeline{
   agent any 
    tools{
     mavin "M2_HOME"
    }
       stages{
        stage ("maven1"){
          steps{
            sh "mvn clean validate compile install test package"
        
          }

        }
      }

}



