
Copy code
pipeline {
    agent any 
    
    tools {
        maven 'M2_HOME'
    }
    
    stages {
        stage('SonarQube Scan') {
            steps {
                script {
                    // Set SonarQube project key and organization
                    def scannerHome = tool 'SonarQubeScanner'
                    withSonarQubeEnv('sonarQube') {
                        sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=simonabeka89_Geo-app -Dsonar.organization=simonabeka_Geo-app"
                    }
                }
            }
        }
        
        stage('Maven Build and Test') {
            steps {
                sh "mvn clean validate compile install test package"
            }
        }
        
        stage('Upload Artifact to Artifactory') {
            steps {
                sh '''
                   curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T target/bio*.jar "http://ec2-54-236-43-92.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"
                '''
            }
        }
    }